# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 14:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tellimus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kuupaev', models.DateField(verbose_name='Tellimuse kuupäev')),
                ('kogus', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Tellimused',
            },
        ),
        migrations.CreateModel(
            name='Toode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nimetus', models.CharField(max_length=70)),
                ('hind', models.FloatField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Tooted',
            },
        ),
        migrations.AddField(
            model_name='tellimus',
            name='toode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raport.Toode'),
        ),
    ]
